version: "3.8"
services: 
  t211math341:
    container_name: t211math341
    build:
      context: .
      args:
        - JULIA_VERSION=1.6.2
    ports: 
      - "1234:1234"
    volumes: 
      - .:/home/julia/project
